# Sobre los autores {-}

## Felipe Bedoya {-}

Politólogo de la Pontificia Universidad Católica del Perú. Diplomado en Industrias Extractivas y Desarrollo por la PUCP y Políticas Públicas por la Universidad del Pacífico. Nacido en Lima, Perú. Cuenta con experiencia profesional en la gestión de proyectos de desarrollo y gestión de recursos naturales con organismos internacionales y organizaciones de la sociedad civil. Anteriormente ha llevado algunos cursos de R y quisiera usarlo de manera más recurrente en el análisis y gestión de información. Tiene interés en áreas de gestión y análisis de información social y económica para la implementación de proyectos sociales y alianzas estratégicas multi-actor que promuevan el desarrollo sostenible.

## Christian Reyes {-}

Politólogo de la Universidad Antonio Ruiz de Montoya. Previo al taller no ha tenido experiencia en el uso de R para el análisis de datos, pero sí el uso de herramientas como Microsoft Excel. Sus últimas experiencias laborales fueron dentro del sector público (Ministerio de Transportes y Comunicaciones, y Ministerio de Vivienda, Construcción y Saneamiento) realizando labores de elaboración y análisis de encuestas y cuestionarios, monitoreo del curso virtual “Programa para Formadores de Integridad” y Seguimiento al Plan de Lucha Contra la Corrupción del sector Vivienda. Le interesan los temas de sistemas electorales, participación y representación política, ética e integridad, entre otros.

## Leanna Sofía de los Ángeles Zúñiga Montaño {-}

Politóloga de la Universidad Antonio Ruiz de Montoya (UARM) y becada por la Alianza del Pacífico (2015) para llevar estudios en la Pontificia Universidad Javeriana de Bogotá. Tiene  conocimientos en políticas públicas, gestión pública, ciudadanía y comunicación para transformar conflictos e investigación académica. 
Se ha desempeñado en el sector privado como encargada de procesos de selección para voluntariado en la Fundación Internacional América Solidaria Internacional y en el sector público como analista en gestión y analista en políticas públicas en instituciones como Ministerio del Interior, Ministerio de Desarrollo e Inclusión Social- Programa Nacional de Alimentación Escolar Qali Warma, Ministerio de Educación y la Superintendencia Nacional de Educación Superior Universitaria-SUNEDU. 
Previo al taller no ha tenido experiencia en el uso de R para el análisis de datos, por lo que se encuentra interesada en aprender y emplearlo como herramienta para investigación y la gestión del conocimiento. 

## Samuel Calderon {-}

Politólogo de la Universidad Antonio Ruiz de Montoya. Fue el encargado de dictar el taller. Actualmente trabaja en la Superintendencia Nacional de Educación Universitaria - SUNEDU como miembro del Equipo Técnico Normativo de la Dirección de Licenciamiento. Aprendió a usar R el año 2019 y desde entonces ha tratado de “convertir” a otras personas. Miembro de la organización DecideBien, colabora ocasionalmente en iniciativas de código abierto. Proviene de Lima, Perú. Su experiencia laboral ha sido siempre en el sector público (Instituto Nacional de Estadística e Informática, Ministerio de Salud, Escuela Nacional de Administración Pública, Ministerio de Vivienda, Ministerio de Educación, SUNEDU). Tiene interés en los temas de educación superior, organizaciones electorales y datos abiertos.

